feat: add ability to delete specific tag
project-zot/zui pull request #391
Opened 2023-11-14 17:53 UTC by eviishondell

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-15 19:21 UTC, raulkele requested changes

2023-11-15 19:21 UTC, raulkele commented on package.json
Please don't add or change packages unless they are required for the implementation

2023-11-15 19:21 UTC, raulkele commented on src/components/Repo/RepoDetails.jsx
> +    const confirmed = window.confirm('Are you sure you want to delete this repo?');
We implemend dialogs using MUI's dialog component, not the native window API, check FilterDialog used in the ExplorePage for example.

2023-11-15 19:21 UTC, raulkele commented on src/components/Repo/RepoDetails.jsx
> +      const apiUrl = `http://localhost:3000/v2/${name}/manifests/`;
We declare our endpoints inside the api.js file. and send requests using axios not fetch. Check the api.js file and usage of api thought the project for examples.
Also, the backend host is declared in the hosts.js file, don't hardcode it inside code

2023-11-15 19:21 UTC, raulkele commented on src/components/Repo/RepoDetails.jsx
> +            console.log('Repo deleted successfully');
don't leave console logs inside code after finishing implementation

2023-11-15 19:21 UTC, raulkele commented on src/components/Shared/TagCard.jsx
> +            onClick={() => {
In general, if your function is longer than 1 line, you want to declare it outside the JSX. Also, same thing abound using the window.confirm api

2023-11-15 19:21 UTC, raulkele commented on src/components/Shared/TagCard.jsx
> +                const apiUrl = `http://localhost:3000/v2/${repoName}/manifests/${tag}`;
api.js for backend requests

2023-11-15 19:21 UTC, raulkele commented on src/host.js
> +  auto: false,
don't push this, keep only on local

2023-11-15 19:21 UTC, raulkele commented on src/setupProxy.js
I'm not sure what this is but it definitely shouldn't be here

2023-11-15 19:28 UTC, raulkele commented
Also, you need to squash your commits so you only have 1

2023-11-15 19:33 UTC, eviishondell commented on package.json
just reverted it back, didn't realize i changed it sorry!!

2023-12-17 19:57 UTC, andaaron commented
Superseded by https://github.com/project-zot/zui/pull/401

2023-12-17 19:57 UTC, closed without merging

2023-12-19 18:19 UTC, rchincha commented
@eviishondell Thanks for your PR.

2023-12-19 18:27 UTC, eviishondell commented
> @eviishondell Thanks for your PR.

No problem!