feat: added button to delete tag
project-zot/zui pull request #401
Opened 2023-12-08 16:20 UTC by peusebiu

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-14 13:17 UTC, raulkele requested changes

2023-12-14 13:17 UTC, raulkele commented on src/api.js
> +    `/v2/_zot/ext/search?query={ExpandedRepoInfo(repo:"${name}"){Images {Manifests {Digest Platform {Os Arch} Size} Vulnerabilities {MaxSeverity Count} Tag LastUpdated Vendor IsDeletable } Summary {N
Please mirror this change in the test-constants file used by the integration tests

2023-12-14 13:17 UTC, raulkele commented on src/components/Repo/RepoDetails.jsx
> +    let newTags = tags.filter((tag) => tag.tag !== removed);
You can use functional setter for the tags state variable

2023-12-14 13:17 UTC, raulkele commented on src/components/Repo/Tabs/Tags.jsx
> +  const { tags, repoName, handleDeleteTag } = props;
rename "handleDeleteTag" property to "onTagDelete" or something similar. Same thing for "TagCard" component

2023-12-14 13:17 UTC, raulkele commented on src/components/Shared/ConfirmDialog.jsx
> +export default function ConfirmDialog(props) {
rename this component to something like "DeleteTagConfirmDialog" since it is specific for tags currently.

2023-12-14 13:17 UTC, raulkele commented on src/components/Shared/ConfirmDialog.jsx
> +import * as React from 'react';
prefer to use the 
"import React from 'react'" syntax here

2023-12-14 13:17 UTC, raulkele commented on src/components/Shared/ConfirmDialog.jsx
> +        <Button data-testid="cancel-delete" variant="contained" onClick={() => onClose()} color="primary">
can use "onClick={onClose}" directly

2023-12-14 13:17 UTC, raulkele commented on src/components/Shared/DeleteTag.jsx
> +    <div>
can use react fragment instead of empty div "<></>"

2023-12-14 16:02 UTC, peusebiu commented
@raulkele  fixed all comments, thank you!

2023-12-14 16:39 UTC, andaaron approved these changes

2023-12-14 19:13 UTC, rchincha approved these changes
lgtm

2023-12-15 23:32 UTC, merged

2023-12-19 21:19 UTC, rchincha commented
Thanks @eviishondell for PR #391 
This PR was inspired by your work on that PR.