Updated the UI to look like the Figma UI
project-zot/zui pull request #81
Opened 2022-09-14 12:49 UTC by ameliamariabreda

**What type of PR is this?**

**Which issue does this PR fix**:
Fixes the UI to look like the latest version of the mockups

**What does this PR do / Why do we need it**:
Closes #75 

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-14 13:49 UTC, raulkele requested changes

2022-09-14 13:49 UTC, raul-kele-qubiz commented on src/components/PreviewCard.jsx
>    const verifiedCheck = () => {
rename function to 'vulnerabilityChip' or something similar

2022-09-14 13:49 UTC, raulkele commented on src/components/PreviewCard.jsx
> +  const SignatureCheck = () => {
camelCase the function name

2022-09-14 13:49 UTC, raul-kele-qubiz commented on src/components/RepoCard.jsx
>    const verifiedCheck = () => {
rename function as mentioned above

2022-09-14 13:49 UTC, raul-kele-qubiz commented on src/components/RepoDetails.jsx
> +    const noneVulnerability = <Chip label="None Vulnerability" sx={{backgroundColor: "#E8F5E9",color: "#388E3C",fontSize: "0.8125rem",}} variant="filled" onDelete={() => { return; }} deleteIcon={ <Pe
as above

2022-09-14 13:49 UTC, raul-kele-qubiz commented on src/host.js
> +  auto:false,
We shouldn't commit dev env changes to host.js

2022-09-15 11:04 UTC, raul-kele-qubiz commented on src/components/ExploreHeader.jsx
> +          <div></div>
Is there a reason for the empty div?

2022-09-15 11:07 UTC, ameliamariabreda commented on src/components/ExploreHeader.jsx
> +          <div></div>
nope. I forgot about it

2022-09-15 11:12 UTC, ameliamariabreda commented on src/components/ExploreHeader.jsx
> +          <div></div>
yes, it keeps the header path in the center of the header

2022-09-15 11:24 UTC, raulkele approved these changes

2022-09-15 11:47 UTC, merged