Got ready the tag page and the vulnerabilities details. Put N/A in the places where data is needed for the release. Commented the code that rendered details that API will not provide untill the release (layers, dependencies, vulnerability and signatures for chips, filters and sorting in explore, rating, downloads and bookmarks). Used encoding for repo with / character in the name
project-zot/zui pull request #82
Opened 2022-09-16 14:58 UTC by ameliamariabreda

**What type of PR is this?**
feature

**Which issue does this PR fix**:
Closes #73 

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-19 12:07 UTC, raulkele requested changes

2022-09-19 12:07 UTC, raul-kele-qubiz commented on src/components/Explore.jsx
> +                          <Grid item xs={0}>
Here we should just remove the Grid element if we are no longer using it

2022-09-19 12:07 UTC, raul-kele-qubiz commented on src/components/ExploreHeader.jsx
> +import { Padding } from "@mui/icons-material";
Remove unused import

2022-09-19 12:13 UTC, ameliamariabreda commented on src/components/Explore.jsx
> +                          <Grid item xs={0}>
Will need it when filter functionality will be added.

2022-09-21 09:20 UTC, raulkele approved these changes

2022-09-21 09:21 UTC, merged